// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTgFfmgMGqSyHjo0IdF2fxotkqtUn2_cs',
    appId: '1:567662902037:web:a5d8c1f48a2719c2cf071c',
    messagingSenderId: '567662902037',
    projectId: 'c12-track-app',
    authDomain: 'c12-track-app.firebaseapp.com',
    storageBucket: 'c12-track-app.appspot.com',
    measurementId: 'G-MK1EPVJNLR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuEAV3A_l27AzaOlsHXdRKTX5094OjZgo',
    appId: '1:567662902037:android:1fc04a9ce186f80dcf071c',
    messagingSenderId: '567662902037',
    projectId: 'c12-track-app',
    storageBucket: 'c12-track-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4XmebqamQfPo9PQg1yL6NTbMBBTj7bbo',
    appId: '1:567662902037:ios:329b5355a7785926cf071c',
    messagingSenderId: '567662902037',
    projectId: 'c12-track-app',
    storageBucket: 'c12-track-app.appspot.com',
    iosBundleId: 'com.example.c12Track',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4XmebqamQfPo9PQg1yL6NTbMBBTj7bbo',
    appId: '1:567662902037:ios:44c3d97941dff25dcf071c',
    messagingSenderId: '567662902037',
    projectId: 'c12-track-app',
    storageBucket: 'c12-track-app.appspot.com',
    iosBundleId: 'com.example.c12Track.RunnerTests',
  );
}
